### ISSUE TITLE
Cannot generate PDF from Dokku Hosted Instance

### ISSUE THREAD

**Issue by buff0k** [laws-africa/indigo#1335]
When I try to save an Act as PDF I get an Nginx Error response 500.

The Dokku Logs for the App show:

2021-10-04T15:37:57.162345635Z app[web.1]: 2021-10-04 15:37:56,873 ERROR log 182 140194685201224 Internal Server Error: /api/documents/26.pdf
2021-10-04T15:37:57.162408914Z app[web.1]: Traceback (most recent call last):
2021-10-04T15:37:57.162422464Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2021-10-04T15:37:57.162435315Z app[web.1]:     response = get_response(request)
2021-10-04T15:37:57.162447398Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
2021-10-04T15:37:57.162460040Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2021-10-04T15:37:57.162472542Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
2021-10-04T15:37:57.162486022Z app[web.1]:     response = response.render()
2021-10-04T15:37:57.162498245Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 106, in render
2021-10-04T15:37:57.162510817Z app[web.1]:     self.content = self.rendered_content
2021-10-04T15:37:57.162522900Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
2021-10-04T15:37:57.162535612Z app[web.1]:     ret = renderer.render(self.data, accepted_media_type, context)
2021-10-04T15:37:57.162547974Z app[web.1]:   File "/app/.heroku/src/indigo/indigo_api/renderers.py", line 158, in render
2021-10-04T15:37:57.162560825Z app[web.1]:     pdf = exporter.render(data)
2021-10-04T15:37:57.162573677Z app[web.1]:   File "/app/.heroku/src/indigo/indigo_api/exporters.py", line 157, in render
2021-10-04T15:37:57.162586249Z app[web.1]:     return self.to_pdf(html, tmpdir, document=document)
2021-10-04T15:37:57.162620053Z app[web.1]:   File "/app/.heroku/src/indigo/indigo_api/exporters.py", line 246, in to_pdf
2021-10-04T15:37:57.162632905Z app[web.1]:     return self._wkhtmltopdf(args, **options)
2021-10-04T15:37:57.162645267Z app[web.1]:   File "/app/.heroku/src/indigo/indigo_api/exporters.py", line 284, in _wkhtmltopdf
2021-10-04T15:37:57.162658328Z app[web.1]:     raise e
2021-10-04T15:37:57.162670271Z app[web.1]:   File "/app/.heroku/src/indigo/indigo_api/exporters.py", line 279, in _wkhtmltopdf
2021-10-04T15:37:57.162682494Z app[web.1]:     return wkhtmltopdf(*args, **kwargs)
2021-10-04T15:37:57.162694437Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wkhtmltopdf/utils.py", line 104, in wkhtmltopdf
2021-10-04T15:37:57.162706800Z app[web.1]:     return check_output(ck_args, **ck_kwargs)
2021-10-04T15:37:57.162718953Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gevent/subprocess.py", line 348, in check_output
2021-10-04T15:37:57.162731804Z app[web.1]:     raise CalledProcessError(retcode, process.args, output=output)
2021-10-04T15:37:57.162746751Z app[web.1]: subprocess.CalledProcessError: Command '['wkhtmltopdf', '--encoding', 'utf8', '--footer-html', '/app/.heroku/src/indigo/indigo_api/templates/indigo_api/akn/export/pdf_footer_akn.html', '--footer-line', '--footer-spacing', '5.00', '--header-font-name', 'Georgia, "Times New Roman", serif', '--header-font-size', '8', '--header-left', '[section]', '--header-line', '--header-right', 'South Africa', '--header-spacing', '5.00', '--margin-bottom', '31mm', '--margin-left', '25.60mm', '--margin-right', '25.60mm', '--margin-top', '31.30mm', '--page-size', 'A4', '--quiet', '--allow', '/tmp/tmpx5ry1oie', '--allow', '', '--allow', '/app/staticfiles', 'cover', 'file:///tmp/tmpxppgkyre.html', 'toc', '--xsl-style-sheet', '/app/.heroku/src/indigo/indigo_api/templates/indigo_api/akn/export/pdf_toc_akn.xsl', 'file:///tmp/tmpx5ry1oie/tmphhycl2z1.html', '-']' returned non-zero exit status 1.

**Comment by buff0k** [comment]
Update, this issue can be replicated in dev deployments on various Python versions, attached sample traceback
[Debug Report - PDF Export Failure.pdf](https://github.com/laws-africa/indigo/files/7721658/Debug.Report.-.PDF.Export.Failure.pdf)
.

**Comment by longhotsummer** [comment]
This is caused by wkhtmltopdf failing. Do the logs show any output from wkhtmltopdf just before the exception is raised?

wkhtmltopdf is horribly flaking and we're moving away from it, but it will be a good few months before those changes make it back into indigo.

**Comment by buff0k** [comment]
I can't see any output from wkhtmltopdf, I will close this issue unless I find any way of pulling logs from wkhtmltopdf
