### ISSUE TITLE
update_countries_plus - broken

### ISSUE THREAD

**Issue by buff0k** [laws-africa/indigo#1374]
I have tested this issue with various python versions and installations (dokku, bare metal, dev and production), and can confirm that python manage.py update_countries_plus fails with following traceback:

python manage.py update_countries_plus
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/countries_plus/management/commands/update_countries_plus.py", line 10, in handle
    num_updated, num_created = update_geonames_data()
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/countries_plus/utils.py", line 218, in update_geonames_data
    return parse_geonames_data(r.iter_lines())
  File "/home/indigo/.pyenv/versions/3.6.5/lib/python3.6/site-packages/countries_plus/utils.py", line 235, in parse_geonames_data
    if line[0] == "#":
IndexError: string index out of range

I suspect a change to geonames.org dataset causes this to fail.

Current temporary workaround (For new deployments) - python manage.py loaddata countries.json (Will load ZA and Nam from the countries.json file).

Can anyone confirm similar issue?

**Comment by buff0k** [comment]
Updated workaround, updating the utils.py for the django-countries-plus package as per @jeyeong on https://github.com/cordery/django-countries-plus/issues/15:

Edit the django-countries-plus uitls.py (on debian should be: /usr/local/lib/python3.9/dist-packages/countries_plus/utils.py around line ~235
![149597687-747c6f6a-aa58-499d-a99d-ba8385822271](https://user-images.githubusercontent.com/20315210/149661013-20380daa-a053-4fed-8136-241c21844e8e.png)
