### ISSUE TITLE
Cannot Compile SCSS

### ISSUE THREAD

**Issue by buff0k** [laws-africa/indigo#1560]
When running: 
python3 manage.py compilescss

Following Error Occurs:
Traceback (most recent call last):
  File "/root/indigo/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/dist-packages/sass_processor/management/commands/compilescss.py", line 162, in handle
    self.parse_template(template_name)
  File "/usr/local/lib/python3.9/dist-packages/sass_processor/management/commands/compilescss.py", line 275, in parse_template
    self.compile_sass(sass_filename, node.path)
  File "/usr/local/lib/python3.9/dist-packages/sass_processor/management/commands/compilescss.py", line 290, in compile_sass
    content = sass.compile(**compile_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sass.py", line 22, in compile
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sass'

**Comment by longhotsummer** [comment]
We've switched to using [dart sass](https://sass-lang.com/install). The easiest is to run `npm install -g sass`

**Comment by longhotsummer** [comment]
I've updated the docs.

**Comment by buff0k** [comment]
Thank you @longhotsummer , this was the issue, sorted, will update downstream how-to
