### ISSUE TITLE
ValueError: Invalid FRBR URI: /za/act/1980/01/main

### ISSUE THREAD

**Issue by buff0k** [laws-africa/indigo#1578]
I have been playing around with a docker-compose deployment of Indigo v17.0.0 for production testing, however I have now hit a wall as relates to the above error each time I try and import a PDF to test with.

Initially also had to add ghostscript to the container which never seemed to be an issue in LXC, regardless, sure @longhotsummer will see exactly where I am going wrong here.

If it will help: https://github.com/buff0k/indigo-docker

indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:21,170 INFO base 29 140208870046976 Processing upload: filename='37539act4of2014employservices7apr2014.pdf', content type=application/pdf
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:21,170 INFO base 29 140208870046976 Processing upload as a PDF file
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:21,170 INFO base 29 140208870046976 Copying uploaded file 37539act4of2014employservices7apr2014.pdf to temp file /tmp/tmpfcv90h3e
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:22,078 INFO pipeline 29 140208870046976 Running ['pdftotext', '-enc', 'UTF-8', '-nopgbrk', '-raw', '-x', '33', '-y', '88', '-W', '440', '-H', '714', '/tmp/tmpfcv90h3e', '-']
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:22,127 INFO pipeline 29 140208870046976 Subprocess exit code: 0, stdout=49929 bytes, stderr=0 bytes
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:22,147 INFO pipeline 29 140208870046976 Running ['bundle', 'exec', 'slaw', 'parse', '--section-number-position', 'after-title', '--grammar', 'za', '--input', 'text', '--ascii', '/tmp/tmpp22f4mam.txt']
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:24,432 INFO pipeline 29 140208870046976 Subprocess exit code: 0, stdout=92372 bytes, stderr=100 bytes
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:24,433 INFO pipeline 29 140208870046976 Stderr: /usr/local/bundle/gems/slaw-12.0.0/lib/slaw/parse/builder.rb:114: warning: URI.unescape is obsolete
indigo-docker-single-docker-indigo-1    |
indigo-docker-single-docker-indigo-1    | 2022-10-13 09:32:24,448 ERROR works 29 140208870046976 Error during import: Invalid FRBR URI: /za/act/1980/01/main
indigo-docker-single-docker-indigo-1    | Traceback (most recent call last):
indigo-docker-single-docker-indigo-1    |   File "/src/indigo/indigo_app/views/works.py", line 992, in form_valid
indigo-docker-single-docker-indigo-1    |     importer.import_from_upload(upload, document, self.request)
indigo-docker-single-docker-indigo-1    |   File "/src/indigo/indigo_api/importers/base.py", line 185, in import_from_upload
indigo-docker-single-docker-indigo-1    |     self.import_from_pdf(upload, doc)
indigo-docker-single-docker-indigo-1    |   File "/src/indigo/indigo_api/importers/base.py", line 239, in import_from_pdf
indigo-docker-single-docker-indigo-1    |     self.import_upload_with_context(upload, doc, context)
indigo-docker-single-docker-indigo-1    |   File "/src/indigo/indigo_api/importers/base.py", line 267, in import_upload_with_context
indigo-docker-single-docker-indigo-1    |     doc.reset_xml(context.xml_text, from_model=True)
indigo-docker-single-docker-indigo-1    |   File "/src/indigo/indigo_api/models/documents.py", line 497, in reset_xml
indigo-docker-single-docker-indigo-1    |     self.copy_attributes(from_model)
indigo-docker-single-docker-indigo-1    |   File "/src/indigo/indigo_api/models/documents.py", line 451, in copy_attributes
indigo-docker-single-docker-indigo-1    |     self.doc.frbr_uri = self.frbr_uri
indigo-docker-single-docker-indigo-1    |   File "/usr/local/lib/python3.8/site-packages/cobalt/akn.py", line 393, in frbr_uri
indigo-docker-single-docker-indigo-1    |     for component, element in self.components().items():
indigo-docker-single-docker-indigo-1    |   File "/usr/local/lib/python3.8/site-packages/cobalt/akn.py", line 438, in components
indigo-docker-single-docker-indigo-1    |     frbr_uri = FrbrUri.parse(self.meta.identification.FRBRWork.FRBRthis.get('value'))
indigo-docker-single-docker-indigo-1    |   File "/usr/local/lib/python3.8/site-packages/cobalt/uri.py", line 202, in parse
indigo-docker-single-docker-indigo-1    |     raise ValueError("Invalid FRBR URI: %s" % s)
indigo-docker-single-docker-indigo-1    | ValueError: Invalid FRBR URI: /za/act/1980/01/main

**Comment by buff0k** [comment]
For testing, tried with v17.1.0 with same result.

**Comment by buff0k** [comment]
v17.2.1 does not have this issue, additionally previous bug with regards to creating PDF now resolved, curiouser and curiouser, I suspect something regarding the move to docpipe, I note, however, the need to install ghostscript (ps2pdf)

**Comment by buff0k** [comment]
Can cconfirm this issue persists in LXC and bare-metal deployments on both v17.0.0 and v17.1.0.

v17.2.0 and v17.2.1 do not have this issue

**Comment by longhotsummer** [comment]
Hi. Can you confirm the version of `slaw` installed via rubygems? Run `slaw --version`.

**Comment by buff0k** [comment]
Hi @longhotsummer, it shows slaw 12.0.0 (which is the same version in 17.0.0, 17.1.0, 17.2.0 and 17.2.1)

It shows slaw 12.0.0

**Comment by longhotsummer** [comment]
I suspect the problem here is that it should be slaw 13.0.0.

**Comment by buff0k** [comment]
You are correct, I have implemented the following workaround in the dockerfile at https://github.com/buff0k/indigo-docker
RUN sed -i "s/slaw (12.0.0)/slaw (13.0.0)/" ./Gemfile.lock
RUN sed -i "s/slaw (~> 12.0)/slaw (~> 13.0)/" ./Gemfile.lock
RUN sed -i "s/gem 'slaw', '~> 12.0'/gem 'slaw', '~> 13.0'/" ./Gemfile
This resolves the issue from the current 17.0.0 git clone.

Should I do a pull request on the 17.0.0 branch?
