### ISSUE TITLE
Bug attaching annotation

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#988]
https://edit.laws.africa/documents/3736/

```
2020-03-18 08:25:43,027 ERROR misc 340 140670329686088 JS error: Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': There is no child at offset 343.
URL: https://edit.laws.africa/documents/3736/
File: https://edit.laws.africa/static/app.a9d567806a28.js @ 8774:13

Error: Failed to execute 'setEnd' on 'Range': There is no child at offset 343.
    at Object.Indigo.dom.textPositionToRange (https://edit.laws.africa/static/app.a9d567806a28.js:8774:13)
    at Object.Indigo.dom.selectorsToRange (https://edit.laws.africa/static/app.a9d567806a28.js:8649:26)
    at https://edit.laws.africa/static/app.a9d567806a28.js:8633:25
    at Object.Indigo.dom.withoutForeignElements (https://edit.laws.africa/static/app.a9d567806a28.js:8558:14)
    at Object.Indigo.dom.targetToRange (https://edit.laws.africa/static/app.a9d567806a28.js:8632:23)
    at child.display (https://edit.laws.africa/static/app.a9d567806a28.js:9276:26)
    at https://edit.laws.africa/static/app.a9d567806a28.js:9515:15
    at Array.forEach (<anonymous>)
    at child.renderAnnotations (https://edit.laws.africa/static/app.a9d567806a28.js:9514:24)
    at Object.<anonymous> (https://edit.laws.africa/static/app.a9d567806a28.js:9477:14)
```

**Comment by longhotsummer** [comment]
Additionally, the error email to admins is not being sent.

**Comment by longhotsummer** [comment]
> Additionally, the error email to admins is not being sent.

This has been resolved.

**Comment by goose-life** [comment]
@longhotsummer is this the same bug? (https://edit.laws.africa/documents/2813/)
`Error: End offset of position selector is out of range`

**Comment by longhotsummer** [comment]
Pushed another fix that resolves this.
